### ISSUE TITLE
Calling single entity / resource

### ISSUE THREAD

**Issue by michsk** [curiosity26/ODataQuery-PHP#6]
I can't seem to find anything to call a single entity, did you already have something for this?

**Comment by curiosity26** [comment]
To get a single entity you have to use a filter to specify which entity you are looking for. Usually an ID field on the entity is the best way to go about this. However you could use a pager object to set the limit to 1 and that would return the first entity from the list.

**Comment by michsk** [comment]
I havent read the full spec of OData, but does a collection return a full resource? If so than your suggestion would indeed work. Altough i have now implemented the option to call trough the ID.

**Comment by curiosity26** [comment]
Yep, according to OData, a collection of entities is returned until the
default upper limit, which I believe is 500. OData specs recommend using a
Filter to specify which entity by id you wish to get.
